/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moonleaf1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author lenovo
 */
public class frame1 extends javax.swing.JFrame {
     Connection  conn= Moonleaf1.ConnecrDb();
    OraclePreparedStatement pst= null ;
    OracleResultSet rs= null; 
    

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
         Toolkit  toolkit= getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size .height/2 - getHeight()/2);
        
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        basic = new javax.swing.JButton();
        coffee = new javax.swing.JButton();
        chocolate = new javax.swing.JButton();
        milk = new javax.swing.JButton();
        yakult = new javax.swing.JButton();
        thaimilktea = new javax.swing.JButton();
        brownsugar = new javax.swing.JButton();
        fruit = new javax.swing.JButton();
        special = new javax.swing.JButton();
        lemonade = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        payment = new javax.swing.JButton();
        exiit = new javax.swing.JButton();
        add2 = new javax.swing.JButton();
        neww = new javax.swing.JButton();
        INVTRY = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelClose5 = new javax.swing.JLabel();
        JLabelMin5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sales = new javax.swing.JButton();
        account = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 0), new java.awt.Color(153, 204, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(1238, 773));
        jPanel1.setPreferredSize(new java.awt.Dimension(1238, 773));

        basic.setBackground(new java.awt.Color(0, 0, 0));
        basic.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        basic.setForeground(new java.awt.Color(255, 255, 255));
        basic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonleaf1/Basic.jpg"))); // NOI18N
        basic.setBorder(null);
        basic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicActionPerformed(evt);
            }
        });

        coffee.setBackground(new java.awt.Color(0, 0, 0));
        coffee.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        coffee.setForeground(new java.awt.Color(255, 255, 255));
        coffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonleaf1/Coffee.jpg"))); // NOI18N
        coffee.setBorder(null);
        coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeActionPerformed(evt);
            }
        });

        chocolate.setBackground(new java.awt.Color(0, 0, 0));
        chocolate.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        chocolate.setForeground(new java.awt.Color(255, 255, 255));
        chocolate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonleaf1/Chocolate.jpg"))); // NOI18N
        chocolate.setBorder(null);
        chocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolateActionPerformed(evt);
            }
        });

        milk.setBackground(new java.awt.Color(0, 0, 0));
        milk.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        milk.setForeground(new java.awt.Color(255, 255, 255));
        milk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonleaf1/Milk.jpg"))); // NOI18N
        milk.setBorder(null);
        milk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milkActionPerformed(evt);
            }
        });

        yakult.setBackground(new java.awt.Color(0, 0, 0));
        yakult.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        yakult.setForeground(new java.awt.Color(255, 255, 255));
        yakult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonleaf1/Yakult.jpg"))); // NOI18N
        yakult.setBorder(null);
        yakult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yakultActionPerformed(evt);
            }
        });

        thaimilktea.setBackground(new java.awt.Color(0, 0, 0));
        thaimilktea.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        thaimilktea.setForeground(new java.awt.Color(255, 255, 255));
        thaimilktea.setBorder(null);
        thaimilktea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thaimilkteaActionPerformed(evt);
            }
        });

        brownsugar.setBackground(new java.awt.Color(0, 0, 0));
        brownsugar.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        brownsugar.setForeground(new java.awt.Color(255, 255, 255));
        brownsugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonleaf1/Brown Sugar.jpg"))); // NOI18N
        brownsugar.setBorder(null);
        brownsugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brownsugarActionPerformed(evt);
            }
        });

        fruit.setBackground(new java.awt.Color(0, 0, 0));
        fruit.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        fruit.setForeground(new java.awt.Color(255, 255, 255));
        fruit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonleaf1/Fruit.jpg"))); // NOI18N
        fruit.setBorder(null);
        fruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitActionPerformed(evt);
            }
        });

        special.setBackground(new java.awt.Color(0, 0, 0));
        special.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        special.setForeground(new java.awt.Color(255, 255, 255));
        special.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonleaf1/Special.jpg"))); // NOI18N
        special.setBorder(null);
        special.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialActionPerformed(evt);
            }
        });

        lemonade.setBackground(new java.awt.Color(0, 0, 0));
        lemonade.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        lemonade.setForeground(new java.awt.Color(255, 255, 255));
        lemonade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonleaf1/Lemonade.jpg"))); // NOI18N
        lemonade.setBorder(null);
        lemonade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonadeActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 255, 0));
        clear.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        clear.setText("clear");
        clear.setBorder(null);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        payment.setBackground(new java.awt.Color(153, 204, 0));
        payment.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        payment.setText("payment");
        payment.setBorder(null);
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });

        exiit.setBackground(new java.awt.Color(255, 0, 0));
        exiit.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        exiit.setForeground(new java.awt.Color(255, 255, 255));
        exiit.setText("exit");
        exiit.setBorder(null);
        exiit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exiitActionPerformed(evt);
            }
        });

        add2.setBackground(new java.awt.Color(153, 204, 0));
        add2.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        add2.setText("Add");
        add2.setBorder(null);
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });

        neww.setBackground(new java.awt.Color(153, 204, 0));
        neww.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        neww.setText("new");
        neww.setBorder(null);
        neww.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newwActionPerformed(evt);
            }
        });

        INVTRY.setBackground(new java.awt.Color(153, 153, 153));
        INVTRY.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        INVTRY.setText("Inventory");
        INVTRY.setBorder(null);
        INVTRY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INVTRYActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 204, 0));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Menu Form");

        jLabelClose5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelClose5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose5.setText("X");
        jLabelClose5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClose5MouseClicked(evt);
            }
        });

        JLabelMin5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JLabelMin5.setForeground(new java.awt.Color(255, 255, 255));
        JLabelMin5.setText("_");
        JLabelMin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabelMin5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabelMin5)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose5)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelClose5)
                            .addComponent(JLabelMin5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(153, 204, 0));
        delete.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        delete.setText("delete");
        delete.setBorder(null);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonleaf1/moonleaflogo (Custom) (Custom).jpg"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 204, 0));
        jLabel10.setText("Moonleaf Cafe");

        sales.setBackground(new java.awt.Color(153, 153, 153));
        sales.setFont(new java.awt.Font("Ink Free", 1, 11)); // NOI18N
        sales.setText("Sales");
        sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesActionPerformed(evt);
            }
        });

        account.setFont(new java.awt.Font("Ink Free", 1, 11)); // NOI18N
        account.setText("Accounts");
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(account)
                        .addContainerGap(752, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thaimilktea)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(neww, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(780, 780, 780))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(872, 872, 872))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exiit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(INVTRY, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sales))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brownsugar)
                            .addComponent(chocolate)
                            .addComponent(fruit)
                            .addComponent(coffee)
                            .addComponent(basic))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lemonade, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(special, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(milk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yakult)))))
                .addContainerGap(810, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basic)
                    .addComponent(lemonade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brownsugar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(milk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coffee)
                    .addComponent(special, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thaimilktea)
                    .addComponent(chocolate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fruit)
                    .addComponent(yakult))
                .addGap(25, 25, 25)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INVTRY)
                    .addComponent(add2)
                    .addComponent(neww)
                    .addComponent(sales))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(delete)
                    .addComponent(exiit)
                    .addComponent(payment)
                    .addComponent(account))
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            String content;
            content=new String(Files.readAllBytes(Paths.get("copy.txt")));
                 
        } catch (IOException ex) {
            Logger.getLogger(frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
          try {
            String content;
            content=new String(Files.readAllBytes(Paths.get("total.txt")));
                    total.setText(content);
        } catch (IOException ex) {
            Logger.getLogger(frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabelClose5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClose5MouseClicked
        // Close
        System.exit(0);
    }//GEN-LAST:event_jLabelClose5MouseClicked

    private void JLabelMin5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelMin5MouseClicked
        // TODO add your handling code here

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_JLabelMin5MouseClicked

    private void basicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicActionPerformed
        // TODO add your handling code here:
        moonleafbasicsize user=new moonleafbasicsize();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_basicActionPerformed

    private void lemonadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonadeActionPerformed
        // TODO add your handling code here:
        lemonademoonleaf user=new lemonademoonleaf();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lemonadeActionPerformed

    private void INVTRYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INVTRYActionPerformed
        // TODO add your handling code here:\
        inventory user=new inventory();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_INVTRYActionPerformed

    private void specialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialActionPerformed
        // TODO add your handling code here:
        Special user=new Special();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_specialActionPerformed

    private void newwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newwActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf=new SimpleDateFormat ("dd-MMM-yy hh:mm:ss aa");
        String datee=sdf.format(new Date()).toString();

        try(PrintWriter writer=new PrintWriter("time.txt", "UTF-8")){
            writer.println(datee);
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        try(PrintWriter writer=new PrintWriter("officialreceipt.txt", "UTF-8")){
            writer.println("                   *Moonleaf Cafe*                     ");
            writer.println("                 "+ datee);
            writer.println("Order"+"                                          "+ "Price");
            writer.close();

            try{
                String content;
                content=new String(Files.readAllBytes(Paths.get("time.txt")));
                Statement st= conn.createStatement();
                st.executeUpdate("INSERT INTO ORDERED VALUES ('"+datee+"','','','','','','')");
                conn.close();
            } catch (Exception e) {

            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(thankyou.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(thankyou.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newwActionPerformed

    private void fruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitActionPerformed
        // TODO add your handling code here:
        fruitmoonleaf user=new fruitmoonleaf();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_fruitActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed

        // TODO add your handling code here:
        conn=Moonleaf1.ConnecrDb();
        SimpleDateFormat sdf=new SimpleDateFormat ("dd-MMM-yy hh:mm:ss aa");
        String datee=sdf.format(new Date()).toString();

        try{

            Statement st= conn.createStatement();
            String content;
            content=new String(Files.readAllBytes(Paths.get("time.txt")));
            st.executeUpdate("UPDATE ORDERED SET STATUS='ADD' WHERE DATEORDERED=to_timestamp('"+content+"')");
            st.executeUpdate("INSERT INTO ORDERED "+ "VALUES('"+datee+"','','','','','','')");
            conn.close();

            try(PrintWriter writer=new PrintWriter("time.txt", "UTF-8")){
                writer.println(datee);
                writer.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_add2ActionPerformed

    private void brownsugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brownsugarActionPerformed
        // TODO add your handling code here:
        brownsugarmoonleaf user=new brownsugarmoonleaf();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_brownsugarActionPerformed

    private void exiitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exiitActionPerformed
        // TODO add your handling code here:
        conn=Moonleaf1.ConnecrDb();
        SimpleDateFormat sdf=new SimpleDateFormat ("dd-MMM-yy hh:mm:ss aa");
        String datee=sdf.format(new Date()).toString();
        
         try{
            String content;
            content=new String(Files.readAllBytes(Paths.get("time.txt")));
            Statement st= conn.createStatement();
            st.executeUpdate("DELETE FROM ORDERED WHERE DATEORDERED= to_timestamp('"+content+"')");
           
            conn.close();
            try(PrintWriter writer=new PrintWriter("time.txt", "UTF-8")){
                writer.println("");

                writer.close();}
        } catch (Exception e) {

        }
        
        Login user=new Login();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_exiitActionPerformed

    private void thaimilkteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thaimilkteaActionPerformed
        // TODO add your handling code here:
        thaimilkteamoonleaf user=new thaimilkteamoonleaf();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_thaimilkteaActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
        paymentmoonleaf user=new paymentmoonleaf();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_paymentActionPerformed

    private void yakultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yakultActionPerformed
        // TODO add your handling code here:
        Yakultmoonleaf user=new Yakultmoonleaf();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_yakultActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void milkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milkActionPerformed
        // TODO add your handling code here:
        moonleafmilk user=new moonleafmilk();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_milkActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_deleteActionPerformed

    private void chocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateActionPerformed
        // TODO add your handling code here:
        moonleafchocolatesizes user=new moonleafchocolatesizes();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_chocolateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf=new SimpleDateFormat ("dd-MMM-yy hh:mm:ss aa");
        String datee=sdf.format(new Date()).toString();
        conn=Moonleaf1.ConnecrDb();

        try{
            String content;
            content=new String(Files.readAllBytes(Paths.get("time.txt")));
            Statement st= conn.createStatement();
            st.executeUpdate("UPDATE ORDERED SET STATUS='CHANGED' WHERE DATEORDERED= to_timestamp('"+content+"')");
            st.executeUpdate("DELETE ORDERED WHERE STATUS='CHANGED'");
            st.executeUpdate("DELETE ORDERED WHERE STATUS='ADD'");
            st.executeUpdate("INSERT INTO ORDERED VALUES ('"+datee+"','','','','','','')");
            conn.close();

            try(PrintWriter writer=new PrintWriter("time.txt", "UTF-8")){
                writer.println(datee);

                writer.close();}

        } catch (Exception e) {

        }

        try(PrintWriter writer=new PrintWriter("copy.txt", "UTF-8")){

        }

        catch (FileNotFoundException ex) {
            Logger.getLogger(Special.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Special.class.getName()).log(Level.SEVERE, null, ex);
        }
        try(PrintWriter writer=new PrintWriter("total.txt", "UTF-8")){
            writer.println("");
            total.setText("");
            total.setText(total.getText());
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Special.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Special.class.getName()).log(Level.SEVERE, null, ex);
        }

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        try(PrintWriter writer=new PrintWriter("officialreceipt.txt", "UTF-8")){
            writer.println("                   *Moonleaf Cafe*                     ");
            writer.println("                 "+ datee);
            writer.println("Order"+"                                          "+ "Price");
            writer.close();} catch (FileNotFoundException ex) {
            Logger.getLogger(Special.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Special.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_clearActionPerformed

    private void coffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeActionPerformed
        // TODO add your handling code here:
        moonleafcoffeesize user=new moonleafcoffeesize();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_coffeeActionPerformed

    private void salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesActionPerformed
        // TODO add your handling code here:
         saleslogin user=new saleslogin();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_salesActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        // TODO add your handling code here:
          acclogin user=new acclogin();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_accountActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
              
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INVTRY;
    private javax.swing.JLabel JLabelMin5;
    private javax.swing.JButton account;
    private javax.swing.JButton add2;
    private javax.swing.JButton basic;
    private javax.swing.JButton brownsugar;
    private javax.swing.JButton chocolate;
    private javax.swing.JButton clear;
    private javax.swing.JButton coffee;
    private javax.swing.JButton delete;
    private javax.swing.JButton exiit;
    private javax.swing.JButton fruit;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton lemonade;
    private javax.swing.JButton milk;
    private javax.swing.JButton neww;
    private javax.swing.JButton payment;
    private javax.swing.JButton sales;
    private javax.swing.JButton special;
    private javax.swing.JButton thaimilktea;
    private javax.swing.JTextField total;
    private javax.swing.JButton yakult;
    // End of variables declaration//GEN-END:variables
}
